version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11.1
        environment:
          NODE_ENV: test
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
    steps:
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm run coverage
      - store_artifacts:
          path: coverage
